name: Build and Release Artifact

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build MSI
        run: ./gradlew packageMsi

      - name: Upload MSI
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: build/compose/binaries/main/msi/steam-start-launcher-1.0.0.msi

      - name: "Publish Pre Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Pre Release"
          files: |
            build/compose/binaries/main/msi/steam-start-launcher-1.0.0.msi
